batch_size: 32
eval_batch_size: 32
dropout: 0.0
lr: 0.0001
num_layers: 5
num_epochs: 50
down_epochs: 50
JK : "none"
task_names:
  - "cora_node"
d_multiple:
  - 2
d_min_ratio:
  - 1
evaluate_names:
  - "cora_node"
dd_multiple:
  - 2
dd_min_ratio:
  - 1