batch_size: 64
eval_batch_size: 64
dropout: 0.0
lr: 0.0001
num_layers: 5
num_epochs: 50
down_epochs: 50
JK : "none"
task_names:
  - "pubmed_node"
  - "FB15K237"
  - "chemblpre"
d_multiple:
  - 2.5
  - 0.4
  - 1
d_min_ratio:
  - 2
  - 0.03
  - 0.2
evaluate_names:
  - "cora_link"
dd_multiple:
  - 1.5
dd_min_ratio:
  - 1